version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'
  - package-ecosystem: 'pub'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'fix(deps)'
