name: routingkit
description: >-
  A lightweight, high-performance router for Dart with elegant API support for static, 
  parameterized, and wildcard routes. Perfect for HTTP servers, API gateways, and application routing.
version: 5.1.0
repository: https://github.com/medz/routingkit

funding:
  - https://github.com/sponsors/medz

topics:
  - router
  - http
  - path-matching
  - trie
  - performance

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ">=4.0.0 <6.0.0"
  test: ^1.24.0
