name: routingkit
description: >-
  Routing Kit
   - Lightweight and fast router.
   - A composable pure function routing kit.
version: 3.0.3
repository: https://github.com/medz/routingkit

funding:
  - https://github.com/sponsors/medz

topics:
  - router
  - routing
  - route
  - fast-router
  - routing-kit

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
