name: routingkit
description: >-
  Routing Kit - Lightweight and fast router for Dart.
version: 2.0.0-dev
repository: https://github.com/medz/routingkit

funding:
  - https://github.com/sponsors/medz

topics:
  - router
  - routing
  - routing-kit
  - radix
  - radix-router

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
