name: routingkit
description: >-
  Routing Kit - router abstractions and built-in high-performance Radix-Trie router driver.
version: 1.0.0
repository: https://github.com/medz/routingkit

funding:
  - https://github.com/sponsors/medz

topics:
  - router
  - routing
  - routing-kit
  - radix
  - radix-router

environment:
  sdk: ^3.3.0

dev_dependencies:
  benchmark_harness: ^2.2.2
  lints: ^4.0.0
  test: ^1.24.0
